name: 🚀 CI
on: [pull_request]

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ci-lint-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔬 Lint
        run: npm run lint

  format:
    name: ⬣ Prettier
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ci-format-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔬 Check Formatting
        run: npm run format:check

  typecheck:
    name: Typescript
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ci-typecheck-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: 📥 Install dependencies
        run: npm ci

      # Enabling the turbo cache causes deployments to fail intermittently.
      # The build step fails with dependency issues. More investigation needed.
      # - name: 💾 Turbo cache
      #   id: turbo-cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       node_modules/.cache/turbo
      #       **/.turbo
      #     key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
      #     restore-keys: |
      #       turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: 📦 Build packages
        run: npm run build

      - name: ✅ Typecheck
        run: npm run typecheck

      - name: 🧑‍💻 CLI manifest check
        run: 'test -z "$(git status --porcelain "packages/cli/oclif.manifest.json" )" || { echo -e "Run npm generate:manifest in packages/cli before pushing new commands or flags. Diff here:\n\n$(git diff)" ; exit 1; }'

  test:
    name: ⬣ Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ci-test-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔬 Test
        run: npm run test
