# This Action is responsible for deploying the default Hydrogen template to Oxygen.
# It is split out from deployments.yml because Oxygen checks for the presence of this specific workflow in the repo.
# TODO: Merge the workflow if/when Oxygen is more lenient.

# Don't change the line below!
#! oxygen_storefront_id: 28966968

name: Oxygen Deployment

on: [pull_request, workflow_dispatch]

jobs:
  deploy:
    name: Deploy to Oxygen
    if: ${{ github.repository_owner == 'shopify' }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: 📥 Install dependencies
        run: npm ci

      # Enabling the turbo cache causes deployments to fail intermittently.
      # The build step fails with dependency issues. More investigation needed.
      # - name: 💾 Turbo cache
      #   id: turbo-cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       node_modules/.cache/turbo
      #       **/.turbo
      #     key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
      #     restore-keys: |
      #       turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: 📦 Build packages
        run: |
          CI=true npm run build:pkg

      - name: 📤 Build and publish the Demo store template to Oxygen
        id: deploy
        uses: shopify/oxygenctl-action@v4
        with:
          path: ./templates/demo-store
          oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_28966968 }}
          oxygen_worker_dir: dist/worker
          oxygen_client_dir: dist/client
          build_command: 'HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL npm run build'
          # Hardcode message and timestamp if manual dispatch
          commit_message: ${{ github.event.head_commit.message || 'Manual deployment' }}
          commit_timestamp: ${{ github.event.head_commit.timestamp || github.event.repository.updated_at }}
          oxygen_health_check: true

      - name: 🐙 Create GitHub deployment
        uses: shopify/github-deployment-action@v1
        if: always()
        with:
          token: ${{ github.token }}
          environment: 'preview'
          preview_url: ${{ steps.deploy.outputs.url }}
          description: ${{ github.event.head_commit.message }}
